services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env

volumes:
  mongo-data:
